name: Naoqi Pepper Env

on:
  release:
    types: [created]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Extract vendored dependencies
      run: ./setup-scripts/extract_deps.sh
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login with Docker registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: ghcr.io/joxcat/naoqi-pepper-env:latest
        push: true
